### ISSUE TITLE
An error occurred while compiling

### ISSUE THREAD

**Issue by jiay7** [awni/transducer#11]
Thank you for the transducer, I got some errors (show blow).

![1652183562(1)](https://user-images.githubusercontent.com/74249633/167622194-db7303ed-a842-419a-86fd-533abd732668.png)

Is this a known issue? How can it be debugged and solved?

Thank you!

**Comment by egorsmkv** [comment]
Check your internet connect to github.com

**Comment by jiay7** [comment]
I have manually installed pybind11, but the following error still occurs.

![1652232392(1)](https://user-images.githubusercontent.com/74249633/167750445-9e82a6f5-e9a1-4778-8dbf-e6d899bb3aec.png)

**Comment by csukuangfj** [comment]
cudaMallocAsync is available in CUDA >= 11.2, I think.

 What is your CUDA toolkit version?

**Comment by jiay7** [comment]
python=3.8 torch verison=1.10.2 cudatoolkit=10.2.89 CUDA version=10.2.

**Comment by jiay7** [comment]
I installed torch verison=1.10.1 cudatoolkit=11.3.1 CUDA version=11.3., and now the code can be compiled normally.
