### ISSUE TITLE
Cuda version

### ISSUE THREAD

**Issue by lianabagh** [awni/transducer#14]
- Generating done (0.0s)
-- Build files have been written to: ./transducer/build/temp.linux-x86_64-cpython-39
[  6%] Building CXX object CMakeFiles/transducer.dir/transducer.cpp.o
[ 13%] Creating directories for 'pybind11'
[ 26%] Building CXX object CMakeFiles/transducer.dir/transducer_cpu.cpp.o
[ 26%] Building CUDA object CMakeFiles/transducer.dir/transducer_cuda.cu.o
[ 33%] Performing download step (git clone) for 'pybind11'
Cloning into 'pybind11'...
.transducer/transducer/transducer_cuda.cu(9): error: A __constant__ variable cannot be marked constexpr

./transducer/transducer/transducer_cuda.cu(10): error: A __constant__ variable cannot be marked constexpr

./transducer/transducer_cuda.cu(364): error: identifier "cudaMallocAsync" is undefined

./transducer/transducer_cuda.cu(386): error: identifier "cudaFreeAsync" is undefined

4 errors detected in the compilation of "/tmp/tmpxft_0004a2b4_00000000-6_transducer_cuda.cpp1.ii".

Hi, 

I get this kind of error, What version of cuda do you use ?

**Comment by awni** [comment]
It looks like 11.5 should have those functions (Async malloc and free) https://docs.nvidia.com/cuda/archive/11.5.0/cuda-runtime-api/group__CUDART__MEMORY__POOLS.html#group__CUDART__MEMORY__POOLS

**Comment by lianabagh** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0

cuda version 11.3, torch version 1.10.1

Still got the same error))
