### ISSUE TITLE
Questions about the reasoning in forward-backward algorithm

### ISSUE THREAD

**Issue by smolendawid** [awni/transducer#2]
I'm looking for the explanation of 3 following cases:
- Why forward and backward passes should return the same (or very similar) likelihoods?

- the forward likelihood is a sum of last forward variable (and calculation step) and the probability of emitting blank token in the last step 
`alphas[T-1, U-1] + log_probs[T-1, U-1, blank]`
however backward likelihood is only the first backward variable value (last calculation step).
`betas[0, 0]`
Why they're different?

- In line 48 in _https://github.com/awni/transducer/blob/master/ref_transduce.py_
`        alphas[t, 0] = alphas[t-1, 0] + log_probs[t-1, 0, blank]
`
why shouldn't we use 
`log_probs[t-1, 0, labels[-1]]`

instead? Isn't it assuming that we expect the last frame to emit a blank token, which is not true?

Could anyone here help me to understand these problems?

**Comment by awni** [comment]
Close, outdated.

**Comment by lazerliu** [comment]
1.They both represents the same sample's likehoods in different compute forms.
2.can think in this opinion : the initial value, alphas[0,0] =1 , betas[T-1,U-1] = log_probs[T-1,U-1, blank]
3. we expect the last decoding to emit a blank and end the decode process, as one frame can be used for infinte decode times.
