### ISSUE TITLE
Question about the gradient computation

### ISSUE THREAD

**Issue by digital10111** [awni/transducer#7]
Thanks, for the great work. 

https://github.com/awni/transducer/blob/5a1c2c776f1667d78c79310616fd2d48bff4e4f5/ref_transduce.py#L92

l couldn't find the log_probs term anywhere in the [paper](https://arxiv.org/pdf/1211.3711.pdf ), specifically equation(20). Could you point me to the equation in the paper, that refers to it.

**Comment by qppp558** [comment]
I think it is because asctually in the code we are computing **dL/d(Log(P))** instead of **dL/dP**.
And **dL/d(Log(P)) = dL/dP * (dP/d(Log(P))) = dL/dP * P**

**Comment by lazerliu** [comment]
> I think it is because asctually in the code we are computing **dL/d(Log(P))** instead of **dL/dP**. And **dL/d(Log(P)) = dL/dP * (dP/d(Log(P))) = dL/dP * P**

record logP
